/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrokerageRouteImport } from './routes/brokerage'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlaylistsSlugRouteImport } from './routes/playlists.$slug'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as VideosSlugRouteImport } from './routes/videos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerageRoute = BrokerageRouteImport.update({
  id: '/brokerage',
  path: '/brokerage',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsSlugRoute = PlaylistsSlugRouteImport.update({
  id: '/playlists/$slug',
  path: '/playlists/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosSlugRoute = VideosSlugRouteImport.update({
  id: '/videos/$slug',
  path: '/videos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/brokerage': typeof BrokerageRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/playlists/$slug': typeof PlaylistsSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/videos/': typeof VideosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/brokerage': typeof BrokerageRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/playlists/$slug': typeof PlaylistsSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/videos': typeof VideosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/admin': typeof AdminRoute
  '/brokerage': typeof BrokerageRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/playlists/$slug': typeof PlaylistsSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/videos/': typeof VideosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/brokerage'
    | '/contact'
    | '/sitemap.xml'
    | '/playlists/$slug'
    | '/videos/$slug'
    | '/videos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/brokerage'
    | '/contact'
    | '/sitemap.xml'
    | '/playlists/$slug'
    | '/videos/$slug'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/admin'
    | '/brokerage'
    | '/contact'
    | '/sitemap.xml'
    | '/playlists/$slug'
    | '/videos/$slug'
    | '/videos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  AdminRoute: typeof AdminRoute
  BrokerageRoute: typeof BrokerageRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PlaylistsSlugRoute: typeof PlaylistsSlugRoute
  VideosSlugRoute: typeof VideosSlugRoute
  VideosIndexRoute: typeof VideosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brokerage': {
      id: '/brokerage'
      path: '/brokerage'
      fullPath: '/brokerage'
      preLoaderRoute: typeof BrokerageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$slug': {
      id: '/playlists/$slug'
      path: '/playlists/$slug'
      fullPath: '/playlists/$slug'
      preLoaderRoute: typeof PlaylistsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$slug': {
      id: '/videos/$slug'
      path: '/videos/$slug'
      fullPath: '/videos/$slug'
      preLoaderRoute: typeof VideosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  AdminRoute: AdminRoute,
  BrokerageRoute: BrokerageRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PlaylistsSlugRoute: PlaylistsSlugRoute,
  VideosSlugRoute: VideosSlugRoute,
  VideosIndexRoute: VideosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
